sonar.verbose=true
sonar.organization=devopsvjkey
sonar.projectKey=devopsvjkey_vjtrend
sonar.projectName=vjtrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
